tap 'buo/cask-upgrade'
tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'aws-iam-authenticator'
brew 'awscli'
brew 'bash-completion'
brew 'docker-completion'
brew 'docker-credential-helper'
brew 'gh'
brew 'git'
brew 'github-keygen'
brew 'graphviz'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'k9s'
brew 'kubectl'
brew 'kubectx'
brew 'postgresql@14'
brew 'rbenv'
brew 'redis', restart_service: :changed
brew 'watch'
brew 'yamllint'
brew 'yq'
