#!/bin/sh

# script/bootstrap: Setup a new laptop at HOVER

# Exit script if any commands return errors (if they exit with non-zero)
set -e

# Work from the user's `Downloads` directory
cd "$HOME/Downloads"

echo
echo "==> Running script/bootstrap…"
echo

SHELL_CONFIG="$HOME/.zshrc"
touch $SHELL_CONFIG

# Check if RSA SSH keys already exist
if [[ -f ~/.ssh/id_rsa ]]; then
  echo "==> Found SSH key in ~/.ssh/id_rsa"
  echo
else
  # Setup Git/GitHub
  echo "==> What email address do you use with your GitHub account?"

  read github_email </dev/tty || {
    github_email=""
  }

  if [[ $github_email == "" ]]; then
    echo "==> ERROR! An email address is required."
    echo "==>        Re-run this script to try again."
    echo
    exit 1
  fi

  # From: https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
  echo "==> Generating SSH key for $github_email …"
  ssh-keygen -t rsa -b 4096 -C "$github_email"
  echo

  echo "==> Starting ssh-agent in the background…"
  eval "$(ssh-agent -s)"
  echo

  # Ensure that SSH config file exists
  touch ~/.ssh/config

  # Add SSH key loading to SSH config
  echo "==> Adding SSH config to automatically load SSH keys"
  grep -qF -- "IdentityFile ~/.ssh/id_rsa" ~/.ssh/config || echo "\n\nHost *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_rsa\n\n" >> ~/.ssh/config
  echo

  # Add SSH private key to the ssh-agent and store passphrase in your keychain
  echo "==> Adding SSH key to ssh-agent and storing passphrase in your keychain"
  ssh-add -K ~/.ssh/id_rsa
  echo

  echo "==> Your browser will be opened to a GitHub SSH Keys settings page…"
  echo "==> You’ll need to paste into the 'Key' field, then click the 'Add SSK Key' button…"
  echo "==> Then, click 'Enable SSO' for that key."
  echo

  echo "==> Press any key to open your browser…"
  read -s -k "?Press any key to continue"

  echo "==> Opening your browser to a GitHub settings page…"
  open https://github.com/settings/ssh/new
  echo

  echo "==> Press any key to continue after you have saved your SSH key on GitHub and enabled SSO…"
  read -s -k "?Press any key to continue"
  echo
fi

echo "==> Copying your public SSH key to clipboard…"
pbcopy < ~/.ssh/id_rsa.pub
echo

# Download strap.sh and run it
echo "==> Downloading strap.sh script from github.com/MikeMcQuaid/strap…"
curl https://raw.githubusercontent.com/MikeMcQuaid/strap/master/bin/strap.sh -o strap.sh
echo

echo "==> Strapping your Mac…"
sh strap.sh
echo

# Delete strap.sh
echo "==> Deleting strap.sh script…"
rm strap.sh
echo

echo "==> Installing asdf…"
brew install asdf
echo

echo "==> Injecting asdf into PATH"
. $(brew --prefix asdf)/asdf.sh
echo

echo "==> Installing ruby asdf plugin"
asdf plugin-list | grep ruby || asdf plugin-add ruby
echo

echo "==> Installing node asdf plugin"
asdf plugin-list | grep nodejs || asdf plugin-add nodejs  
echo

echo "==> Installing yarn asdf plugin"
asdf plugin-list | grep yarn || asdf plugin-add yarn
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
echo

echo "==> Bundling engineering Brewfile to install remaining developer tools and various other niceties…"
curl https://raw.githubusercontent.com/emiliohealth/workstation/main/Brewfile | brew bundle --file=-

# All done!
echo "==> SUCCESS! Your development environment is now bootstrapped!"
echo
